force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Module Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ModuleEnrolled__c/ModuleEnrolled__c.object-meta.xml
<CustomObject>
    <label>Module Enrolled</label>
    <nameField>
        <displayFormat>ME-{0000}</displayFormat>
        <label>Enrollment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modules Enrolled</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ModuleEnrolled__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Modules Enrolled</relationshipLabel>
    <relationshipName>ModulesEnrolled</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ModuleEnrolled__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Modules Enrolled</relationshipLabel>
    <relationshipName>ModulesEnrolled</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AP01_StudentEnrolment.cls
/**
 * @description       : 
 * @author            : Rakshak Rajjoo
 * @last modified on  : 24/01/2022
 * @last modified by  : Rakshak Rajjoo
 * Modifications Log
 * Ver   Date         Author           Modification
 * 1.0   24/01/2022   Rakshak Rajjoo   Initial Version
**/
public with sharing class AP01_StudentEnrolment {
   
    public static void enrolStudent(Id studentId, Id moduleId){
        ModuleEnrolled__c modEnr = new ModuleEnrolled__c(
            Student__c = studentId,
            Module__c = moduleId
        );

        insert modEnr;
    }

    public static List<Student__c> fetchStudentsEnrolled(Id moduleId){
        List<ModuleEnrolled__c> lstModEnr = [SELECT Id, Student__c FROM ModuleEnrolled__c WHERE Module__c = :moduleId];

        Set<Id> setStdId = new Set<Id>();
        for(ModuleEnrolled__c modEnr : lstModEnr){
            setStdId.add(modEnr.Student__c);
        }

        List<Student__c> lstStd = [SELECT Id, Name FROM Student__c WHERE Id IN :setStdId];
        return lstStd;
    }
}