force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Module Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/fields/PassingMark__c.field-meta.xml
<CustomField>
    <fullName>PassingMark__c</fullName>
    <label>Passing Mark</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ModuleEnrolled__c/ModuleEnrolled__c.object-meta.xml
<CustomObject>
    <label>Module Enrolled</label>
    <nameField>
        <displayFormat>ME-{0000}</displayFormat>
        <label>Enrollment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modules Enrolled</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ModuleEnrolled__c/fields/CreditsEarned__c.field-meta.xml
<CustomField>
    <fullName>CreditsEarned__c</fullName>
    <label>Credits Earned</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ModuleEnrolled__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Modules Enrolled</relationshipLabel>
    <relationshipName>ModulesEnrolled</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ModuleEnrolled__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP02_HandlePassFail.cls
/**
 * @description       :
 * @author            : Rakshak Rajjoo
 * @last modified on  : 14/07/2022
 * @last modified by  : Rakshak Rajjoo
 * Modifications Log
 * Ver   Date         Author           Modification
 * 1.0   31/01/2022   Rakshak Rajjoo   Initial Version
 **/
public with sharing class AP02_HandlePassFail {
    /**
     * @description method to pupulate module enrolled status before update
     * @author Rakshak Rajjoo | 14/07/2022
     * @param List<ModuleEnrolled__c> lstMdEnrold
     * @param List<ModuleEnrolled__c> lstMdEnrNew
     **/
    public static void populatePassFail(List<ModuleEnrolled__c> lstMdEnrNew, List<ModuleEnrolled__c> lstMdEnrOld) {
        Set<Id> setModuleId = new Set<Id>();
        for (Integer i = 0; i < lstMdEnrNew.size(); i++) {
            if (lstMdEnrNew[i].CreditsEarned__c != lstMdEnrOld[i].CreditsEarned__c) {
                setModuleId.add(lstMdEnrNew[i].Module__c);
            }
        }
        Map<Id, Module__c> mapMod = new Map<Id, Module__c>([SELECT Id, PassingMark__c FROM Module__c WHERE Id IN :setModuleId]);

        for (Integer i = 0; i < lstMdEnrNew.size(); i++) {
            if (lstMdEnrNew[i].CreditsEarned__c == null) {
                lstMdEnrNew[i].Status__c = 'In Progress';
            } else if (lstMdEnrNew[i].CreditsEarned__c >= mapMod.get(lstMdEnrNew[i].Module__c).PassingMark__c) {
                lstMdEnrNew[i].Status__c = 'Pass';
            } else {
                lstMdEnrNew[i].Status__c = 'Fail';
            }
        }
    }

    /**
     * @description Method to calculate average percentage on student
     * @author Rakshak Rajjoo | 14/07/2022
     * @param List<ModuleEnrolled__c> lstMdEnrNew
     * @param List<ModuleEnrolled__c> lstMdEnrold
     **/
    public static void calculateStudentAveragePercentage(List<ModuleEnrolled__c> lstMdEnrNew, List<ModuleEnrolled__c> lstMdEnrold) {
        //Your code here
    }

    /**
     * @description Method to calculate results (Pass/Fail) of student
     * @author Rakshak Rajjoo | 14/07/2022
     * @param List<ModuleEnrolled__c> lstMdEnrNew
     * @param List<ModuleEnrolled__c> lstMdEnrold
     **/
    public static void calculateStudentResult(List<ModuleEnrolled__c> lstMdEnrNew, List<ModuleEnrolled__c> lstMdEnrold) {
        //Your code here
    }
}